// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyxpulmqxslhegngzlac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5eHB1bG1xeHNsaGVnbmd6bGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTIzNjAsImV4cCI6MjA3MTYyODM2MH0.rrZv1VyKNruLu_vRm48PNn_acAczkWxA3pcrbZJtxds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});